title: darrelln.github.io/dev/
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  This is my description.
baseurl: ""
url: ""
theme: "just-the-docs"
search_enabled: true
color_scheme: light